export const homePageContent = {
    heroText: "Soy Sebastià y trabajo como terapeuta gestalt en Palma de Mallorca.",
    paragraph1: "Entiendo el proceso terapeutico como un encuentro entre dos personas.",
    paragraph2: "{BoxedWordClockWise|Martin Buber} explica magníficamente esta relación yo-tú como un diálogo: “Sin finalidad, sin codicia, sin preconcepto. Donde cada uno tiene la posibilidad de descubrirse a sí mismo sin ser manipulado por el otro”.",
    paragraph3: "Este diálogo se enmarca dentro de la Gestalt. La Gestalt como marco de trabajo, como encuadre.",
    paragraph31: "Hablemos de ella:",
    paragraph4: "{BoxedWordClockWise| Fritz Perls} partía de la base de que todo lo que estamos buscando está ya en el momento presente. Hay por tanto un compromiso profundo con la presencia en el {BoxedWordClockWise2| aquí y ahora}como espacio de trabajo.",
    paragraph5: "Seguimos con la responsabilidad, no como un deber sino un hecho inevitable. Somos los actores responsables de cualquier cosa que hagamos. Nuestra única alternativa es reconocer tal responsabilidad o negarla. Y percatarse de esta verdad, nos cura de nuestras mentiras. Así decía {BoxedWordClockWise2| Claudio Naranjo}.",
    paragraph6: "Responsabilidad y presencia. Seguimos con el {BoxedWordClockWise| darse cuenta}, el percatarse. Darse cuenta de todo lo que nos ocurre, pero sobre todo darse cuenta de que vivimos en un estado enfermo, neurótico.",
    paragraph7: "Es este deterioro del darse cuenta, lo que hay que mirar. Es esta dificultad para percibir la realidad poniendo atención de manera compulsiva en algunos procesos y dejando fuera otros tantos.",
    paragraph8: "Por tanto, tenemos presencia, conciencia y responsabilidad como guías en este camino. Por último y no menos importante, en gestalt la llamamos autoregulación organísmica y es un nombre extravagante para una palabra sencilla: {BoxedWordClockWise| Fe}. Fe en que existen soluciones y que somos capaces de encontrarlas por nosotros mismos. Fe en que hay una pulsión de vida en nuestro interior que nos impulsa a desarrollar nuestro potencial, crecer y alejarnos del sufrimiento. Aunque en ocasiones el camino hacia la autoregulación pueda estar obstruido o sea tortuoso, debemos confiar en que tenemos la capacidad de acceder a ella y encontrar la sanación que buscamos.",
  };